PATCH http://localhost:3333/addresses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NjM3MTUxOCwidXNlcl9pZCI6Ik5MQXRSV1BIWm1WRUJxYmd2QjBvV3M3Sm8yeTIiLCJzdWIiOiJOTEF0UldQSFptVkVCcWJndkIwb1dzN0pvMnkyIiwiaWF0IjoxNzU2MzcxNTE4LCJleHAiOjE3NTYzNzUxMTgsImVtYWlsIjoia2Jyb3duQGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImticm93bkBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.alCE9PH1mO0sv5qr5gub2SucgPBxSWUOVfUxERIsEkmZ-Mt9J6kLaF7QvNR1ygEJTPC75b5_WgxyQ3e3339mQVCeYUEDDdioqrVR0nbZscUs2Kkas8vbBCzFKVGBdijO8-oRD33xBY46UbSIOd8MF18boJFaggSgzbmFmNe4AgJX4Ykqm7yh9dgtHtbJE_AbA9r9l7vNFtAcVhzdKWAMSXu8ujjS4SzBrNpYERZe0PkJHPKp9gVlp_6NPHM39Z6l0TDhUlK5kQ-2BcLYy_-S587PSVlEw-KbATG0xOYsw2CACjbJYjSQ3d2KVJUJruUDYaT2yfz86v5N1Nsr3c--0g

{
    "city": "Atlanta",
    "state": "GA",
    "zip": 30301
}