GET http://localhost:3333/drivers-licenses
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMjQ4ZjQyZjc0YWUwZjk0OTIwYWY5YTlhMDEzMTdlZjJkMzVmZTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NjM3NTE3OSwidXNlcl9pZCI6Ik5MQXRSV1BIWm1WRUJxYmd2QjBvV3M3Sm8yeTIiLCJzdWIiOiJOTEF0UldQSFptVkVCcWJndkIwb1dzN0pvMnkyIiwiaWF0IjoxNzU2Mzc1MTc5LCJleHAiOjE3NTYzNzg3NzksImVtYWlsIjoia2Jyb3duQGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImticm93bkBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.abbRwCIeQmVsm-tGKbC11Kcj3mFU2pNz-GTZraDlCLwc-FHpO5IJgas7GsjNmbcJYO3ASLPO7Q21BUBo4B-964toYN1sJ4IMy5Udfk2JV6LV41DCkq_Dd4sCVKSOh3TqMuGuUY01r4-8oEDQo9gJLuph0BTzStGdfC78mJP9bsm46XZFgbB-scXjZLDFyseqtrT9hq__4L81bjBuEw9PPNMzVIy2oLu6WUFRkR3WeBakkVWI9TkglM4zbBPmbWrW8saI8mngkCLfaYhIZTI_gtGone20s4YvEYkeV8FeEUNncItvs2v4Na8yMl5ZuFEIkv_L4g2plYSY4JQxaOcsyQ