POST http://localhost:3333/booking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NjQ1Mzg2OSwidXNlcl9pZCI6IlNWNDdFdUlpMWNhd3ZDd0dZZ0lKWFdET2FJaDEiLCJzdWIiOiJTVjQ3RXVJaTFjYXd2Q3dHWWdJSlhXRE9hSWgxIiwiaWF0IjoxNzU2NDUzODY5LCJleHAiOjE3NTY0NTc0NjksImVtYWlsIjoiY3N0YW5AZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY3N0YW5AZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.arZLqJx0oYJOd7cPGjHNDDcOWBIABsyD8C8YkeW2f-hgLSqsnURkrhlKY5iwYzKPn0NgTR_xjOPloOylqr3_c29Qhz0WNzMeC96UtWzpVC8ytdNOAtYfGZslCm3tWYQhHXCh7_zUNwwfcMfxCscW10wsqz1H0J35SSIEzZMYzr-TfVUwYD7yhVO61fEH9-qpXwL77r3eMpRmPlt8dTT-ABt2Bg_OY4vHLahkBru1Uv0DPgDCqKf6zhJpT-pTO3FaOYgLgumUZFQpaKVh_kHLTpfEgC0B-5sBmsHqVSDqEL4_CTaChyo13sUeJcVRhmQlFCu_4L6F1WhnUPe97i4yDQ

{
    ""
}