POST http://localhost:3333/users/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMjQ4ZjQyZjc0YWUwZjk0OTIwYWY5YTlhMDEzMTdlZjJkMzVmZTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzAxMTM1MywidXNlcl9pZCI6Inl1cUVKaXBmVFBSaGVxRVhsc2hHSkZqSXpVNzMiLCJzdWIiOiJ5dXFFSmlwZlRQUmhlcUVYbHNoR0pGakl6VTczIiwiaWF0IjoxNzU3MDExMzUzLCJleHAiOjE3NTcwMTQ5NTMsImVtYWlsIjoiY2FtLXN0YW5sZXlAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2FtLXN0YW5sZXlAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.f7MG4O9o6803J6aMaaSa5eKly0MCHg0q7WaKsdd31YRVVCNWoK5K02mpAIGpcF_GWyqXC3Zk-8YJZJ50E0seC67pv4fW3lXW45b1zNQj3MnQaoBgLA1xK_y29aTgqiDmTOfnxA-SWVTgPkA8vofn7fpf3b65PX5So-SllZfmU7luH6RttGZvXO-rM6hJsdCSQkTE8K3poqaLKJuDG81cCKf5rUV59MKYYDWxSzqR2pC61Rw_81mkciKHoFMxNFX4vul92ePUmzVmfT-qbrwoXSVySy3yls64VKYBKw0xbxR0GWaM0itGjLFnzc0iRy_9qiVP98M6_Ar92B0mVOC8dg

{
    "firstName": "cam",
    "lastName": "stanley",
    "email": "cam-stanley@example.com",
    "password": "test123"
}