POST http://localhost:3333/users/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjUwMDZlMjc5MTVhMTcwYWIyNmIxZWUzYjgxZDExNjU0MmYxMjRmMjAiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzkxMzI0OCwidXNlcl9pZCI6InBYTzJGM0g4UEJUeHQ4TEpZWGpGOHZoTks1VTIiLCJzdWIiOiJwWE8yRjNIOFBCVHh0OExKWVhqRjh2aE5LNVUyIiwiaWF0IjoxNzU3OTEzMjQ4LCJleHAiOjE3NTc5MTY4NDgsImVtYWlsIjoiZ3Vlc3RAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZ3Vlc3RAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJjdXN0b20ifX0.sK-GEiM9RnsS__Ww9zFUEF40b6ZkhOYF5HfVfgxbXPFGvSvlYBor-Hlf0ZdV845kVOj1AT82CcMdUQ3AlfGr4Z7OzcX9kwh4ACV-vXWvly7HyDPPbk7O2A7XZ3xAgZhiEHIrtVgfBqEeCA2befVBs8DsKN8GcPr3lNf6-KcDSxsoo_Yui1tSiqEoVK15_mlxMCDr46HxYgrDJolDiSGkBnoe2e2Fy_KEEip1ShIRLHGISshjfF7wA0m_ahEUtTRk4llrQfWPmRYxoJjaHSDPKpiPHxc61Ub8dmBPrDyhqizM7StrwOunO3d97Raj-ijIrzFkIlOjxfvWvZIIVYtRog
{
    "firstName": "ADMIN",
    "lastName": ""
}