GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ1NzQyMywidXNlcl9pZCI6ImxQYVdmYkhvOERNWHNiUVFXTlE3Y0VpRHpxZzIiLCJzdWIiOiJsUGFXZmJIbzhETVhzYlFRV05RN2NFaUR6cWcyIiwiaWF0IjoxNzU3NDU3NDI0LCJleHAiOjE3NTc0NjEwMjQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.nnNgJ5hCrs7w260SxGXNtO8tzlF2brz7lsr3m4G70lSXUdtFnvQYYIdX1bqfM3TbBXct7xv0R4qYYngg4Y9Es97fqOIQKW8um6zCZ7MdtMKwVpLJ1zRcPHJiTgQCXodz-5NFZ-PUuLaxPk2LXQnyZtL_FEOpJP5qry9ZeXjNVldscR95uZElYLziIAfBnMUkRc8nrBnUvlTMf6hge95pWRBSXkgfzdql4YV0Y0Q02oMLwXKfDLjOOjB-P9Z5ibFRpbMszvbnRWCsAoD0Q0Ojw2FneH02txZDoL_XfzvRjGzJyquvOqQDTjLnc3F84WfVJwBIrEqXLY_uSVlDtbbPlg