PATCH http://localhost:3333/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVmMjQ4ZjQyZjc0YWUwZjk0OTIwYWY5YTlhMDEzMTdlZjJkMzVmZTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1Njc4ODIyNiwidXNlcl9pZCI6IlNWNDdFdUlpMWNhd3ZDd0dZZ0lKWFdET2FJaDEiLCJzdWIiOiJTVjQ3RXVJaTFjYXd2Q3dHWWdJSlhXRE9hSWgxIiwiaWF0IjoxNzU2Nzg4MjI2LCJleHAiOjE3NTY3OTE4MjYsImVtYWlsIjoiY3N0YW5AZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY3N0YW5AZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.H4yuO29FbBpWmQ5D7XifQy5QhRD2M3YHgvdv3O9sKKmRv0hnD9RPHHSSk-UggSufx1teHSiyW_8Hr77qWy1I9ZNUKuor6IFC-wS4lIVvBFRL7zEv1FtcxnClYDKZNFKFovThRwp1iZWDcyuG8d9CZXw739RVz8L35XgKFpZXkgfFgk3ELCW53rDMhtwze2WhZVLR0XHceBOTfMWnENFbQiBMKucpQAp_ks7vEaQlbZr5v4arGaBpyqh6LnD7LISik3lFm-0FX7JUsvONJ3eJ4aWpOZWN_VP_XJR4ILYis5mpD2ccRUD8Dqkdc0Hq9Y9MW75Uwosj3XFC1-vFLCAHqA

{
    "firstName": "Cameron",
    "lastName": "Stanley",
    "phone": "(813)255-7532"
}