POST http://localhost:3333/users/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ2MTQxMSwidXNlcl9pZCI6ImxQYVdmYkhvOERNWHNiUVFXTlE3Y0VpRHpxZzIiLCJzdWIiOiJsUGFXZmJIbzhETVhzYlFRV05RN2NFaUR6cWcyIiwiaWF0IjoxNzU3NDYxNDExLCJleHAiOjE3NTc0NjUwMTEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.pS7Ala2is4kd_ebJP8eZZyeZcTPditKOil-Nz1gY8vTBXEpE4AtDlzilDZ3COleIdA-EghqZhgwgiBAj0LvCgjx0zHlA4dnmMAtkW3Bn_wTZ_FCqf3ofsHSniv_dlgojq7pCCK26I2Y_1kFuYpK9znNM1SAUxvFgkcdeglUGXC3k7oZGuvea9NMmGTEhO5FistafW-2J4TgaMBQm71HG8c6AJB5tz5EndzkQqJYMceXSRkYlbnVLRG11Jy-n8r-JdoiOtazJhdmD6U1YIh0s5IhcM9EGPdixtne2gJWOFVYppcR_bd6iC0f71cA95okqOwoMskSi0RlRPzR7kq3hVA

{
    "firstName": "Jane",
    "lastName": "Doe"
}