PATCH http://localhost:3333/vehicles/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NjU3NDI4MywidXNlcl9pZCI6IlNWNDdFdUlpMWNhd3ZDd0dZZ0lKWFdET2FJaDEiLCJzdWIiOiJTVjQ3RXVJaTFjYXd2Q3dHWWdJSlhXRE9hSWgxIiwiaWF0IjoxNzU2NTc0MjgzLCJleHAiOjE3NTY1Nzc4ODMsImVtYWlsIjoiY3N0YW5AZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY3N0YW5AZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CqCct22JXi-5FuDShNNNeE28f-Tu0SFkZXOYgPMCv4nB-8DvWVLlnLFttNYEaXDNp4U42D6U7UTDjHblyYg7L3JzBT9VuWZV-UuMNJM9BQLqMVzT5IDGmL5qluvvQEGMTAeHYJfcuk07XqeTSQczBWYAsDCmCSrcJuCYycxnXfUQyihyZ1bDXeszahZFS6_0RR5Y3DuluJnI2pArTnpCtoBGOscXimi26O7nythhyvY1paf93Wn1Tf_WdlXrgWNbBipY11ToL4IfWbJ_eT4VfuFNmhcenTT-IkavEEE_6lJMVBzHGivkPMApqqxtt-K3Y6wcy1C4G1R5waFMq7NyUw

{
  "make": "Hyundai",
  "modal": "Sonata"
}