GET http://localhost:3333/admin/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ1MjI0OCwidXNlcl9pZCI6Ik54Z2VnSlo0ZGRVQkVtVXp1dW5wUDNEVFZ3azIiLCJzdWIiOiJOeGdlZ0paNGRkVUJFbVV6dXVucFAzRFRWd2syIiwiaWF0IjoxNzU3NDUyMjQ4LCJleHAiOjE3NTc0NTU4NDgsImVtYWlsIjoiY2FtZXJvbi1zdGFubGV5QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNhbWVyb24tc3RhbmxleUBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YCzv6NDrcEyJVMkQ-Vb2XUl7e5F5mfYUwa9AKUX-Cw3k3B_Sn4SrUIYJ1QSF4HEP8yplXnmOLvMlOxX5eADbY9GdxBp3G5Nq6BNF0UI9BUnVxw0c-kZBgmg9zfYW05hBrmxLJ1Jl5XHz7cjZIlRRi_IcGT8l5UDgD5CbZesGojIEUfLa2vdOi7_z7aYMuNH-rZmXTTJib54sbiu8utvd7J9MwfPfUuK75NJgiggnrpmh4td0GOwnxdJy4RlE5PvxDd5uECALbIC-87EvkzH_kkNb-_5rv3fN_47g5FFTGFDUs9Dzu_QfrsLkxWoCj8E7iovaBvodiBBVkYa7E58aNg