GET http://localhost:3333/admin/users/yuqEJipfTPRheqEXlshGJFjIzU73
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ2MDEzMywidXNlcl9pZCI6Ik54Z2VnSlo0ZGRVQkVtVXp1dW5wUDNEVFZ3azIiLCJzdWIiOiJOeGdlZ0paNGRkVUJFbVV6dXVucFAzRFRWd2syIiwiaWF0IjoxNzU3NDYwMTMzLCJleHAiOjE3NTc0NjM3MzMsImVtYWlsIjoiY2FtZXJvbi1zdGFubGV5QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNhbWVyb24tc3RhbmxleUBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ZHCc-vYI9ccOOJSFPM6t7HF4He_X7gKvRbfMQ0zwpVULEPrN4fnOhV8AmqtRye1UBYK4fh0isnp6RLTA8x_tGuvxsWvQEe5gmRHd49uFliscm82_qmYTnwj4wsN6rxylTZTH9OkgR-BgJUt7Rgv0sG-q5UtAUYfdpC7JjyDapWWWdbhhEbKEfXoeE4MZPv7DhO2YG_cfbaodhna_Pfg9RXm63-OJAK7SKQa8D9YfhaCFR2Nnmp_AvePc_o8MnZLeqW0hXmPA87B66eCvKwGzJD_M_jqr_3SsvMvEXb9Zj-9WbSBbrN1buOsEtbbPJl0CxbpMDKJGP6baBIdxrSAsRA