GET http://localhost:3333/admin/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ0NjE3MSwidXNlcl9pZCI6Ik54Z2VnSlo0ZGRVQkVtVXp1dW5wUDNEVFZ3azIiLCJzdWIiOiJOeGdlZ0paNGRkVUJFbVV6dXVucFAzRFRWd2syIiwiaWF0IjoxNzU3NDQ2MTcxLCJleHAiOjE3NTc0NDk3NzEsImVtYWlsIjoiY2FtZXJvbi1zdGFubGV5QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNhbWVyb24tc3RhbmxleUBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Fqi-dooaCLC3jLNJVCdsB6GcdGMD1sLileNPMMYp4cesnbn9Nd46XzkTiQUfsmiG9wD39OBmIpt-TYpIVBz92xnAVxTBaOxJDrOxi1tGBGJ9_D00EyUOQtvszzhVU_r9Ui0CdJP07YmorvniHdjy3UjAzOIvwz6oS6SxDbsvYfSi0KPyJfGPTnh1mvTWdmJ9Vpg9zRHlPRqClGV6YE08y78zool0Qso6VNaOQ-huv9hlquv_cU_lv7FuD9lcexT6f1Ol_9wXxAul5gsEdNLlMmMlJ-TYTRbE-GgwfLLTFX5RGwF-CEAHJw-65ssEyJu2sC6-b3NbTDTHLF0E5UqA5w