PATCH http://localhost:3333/admin/user/lPaWfbHo8DMXsbQQWNQ7cEiDzqg2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzZWU3ZTAyOGUzODg1YTM0NWNlMDcwNTVmODQ2ODYyMjU1YTcwNDYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFvLXJlbnRhbHMiLCJhdWQiOiJyYW8tcmVudGFscyIsImF1dGhfdGltZSI6MTc1NzQ2MTIwMSwidXNlcl9pZCI6Im9kbFBLSnowYVdjNkNoY2hFa1lySWJzZGNBNTMiLCJzdWIiOiJvZGxQS0p6MGFXYzZDaGNoRWtZcklic2RjQTUzIiwiaWF0IjoxNzU3NDYxMjAyLCJleHAiOjE3NTc0NjQ4MDIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW5AdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.WWK1-0jH3Z8pbzf51Sh8U_2ALHMSUAYHW32XK8ID0mLncWX84u7k1BYHfSmee-huryJF-9KAIALlYmAtR2I3d-qoDrK71Q0d6h7Emg4PfxFesKvPeZz3YuhzZDvuqAA2u0DzhTq2jIjDRC8zV-1JsE-icjjXB2RpqshVHgCavshUs8nO50g1PSdWf3LxPdchgkwRm7bJmBwR4S6Wp7iyYRaFFCgxqeHuODQxqgDOtXaRL8CybcbidzSO08SN_462RlCQxID1HUUuSUiB4PFzcfycEY43oMHjcKknTwupKdN6_4Mzyx9DWfAqoHLRBGCC4MBYKHd3kwnZG_Y_xiOUvg

{
  "firstName": "John",
  "lastName": "Doe"
}